version: '3.4'

services:
  chat.ui:
    image: ${DOCKER_REGISTRY-}chatui
    build:
      context: .
      dockerfile: Chat.UI/Dockerfile
    depends_on:
      - sqlserverdb
      - rabbit
      
  sqlserverdb:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Chat_123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"